name: cinema_showtime_selection
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  flutter_native_splash: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/spider_man.jpg
    - assets/images/cappuccino.png
    - assets/images/background_photo.png
    - assets/images/coffee_bean.png
    - assets/svgs/icon.svg
    - assets/rives/logo.riv
    - assets/images/flat_white.png
    - assets/images/mocha.png
    - assets/images/americano.png
    - assets/svgs/buy.svg
    - assets/svgs/profile.svg
    - assets/svgs/coffee_cup.svg
    - assets/svgs/coffee_cup_disable.svg
    - assets/svgs/home.svg
    - assets/svgs/receipt.svg
    - assets/svgs/gift.svg
    - assets/svgs/home_disable.svg
    - assets/svgs/receipt_disable.svg
    - assets/svgs/gift_disable.svg
    - assets/svgs/coffee.svg
    - assets/svgs/location.svg
    - assets/svgs/edit.svg
    - assets/svgs/back.svg
    - assets/svgs/email.svg
    - assets/svgs/phone.svg

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins.ttf
    - family: DM Sans
      fonts:
        - asset: assets/fonts/DMSans.ttf
